name: Deploy All Projects to GitHub Pages

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install Portfolio dependencies
        run: npm ci --legacy-peer-deps
        working-directory: Project2/portfolio
      
      - name: Build Portfolio
        run: npm run build -- --base-href="/AngularTraining/Project2/portfolio/"
        working-directory: Project2/portfolio
      
      - name: Install Student Management dependencies
        run: npm ci --legacy-peer-deps
        working-directory: Assessments/Week6/student-management
      
      - name: Build Student Management
        run: npm run build -- --base-href="/AngularTraining/Assessments/Week6/student-management/"
        working-directory: Assessments/Week6/student-management
      
      - name: Install Day2-portfolio dependencies
        run: npm ci --legacy-peer-deps
        working-directory: Project2/Day2-portfolio
      
      - name: Build Day2-portfolio
        run: npm run build -- --base-href="/AngularTraining/Project2/Day2-portfolio/"
        working-directory: Project2/Day2-portfolio
      
      - name: Create deployment directory
        run: |
          mkdir -p deploy
          cp index.html deploy/
          cp 404.html deploy/
          cp .nojekyll deploy/
          cp -r Phase1 deploy/
          cp -r Phase2 deploy/
          mkdir -p deploy/Project2/portfolio
          cp -r Project2/portfolio/dist/portfolio/browser/* deploy/Project2/portfolio/
          cp -r Project2/Game deploy/Project2/
          mkdir -p deploy/Assessments/Week6/student-management
          cp -r Assessments/Week6/student-management/dist/student-management/browser/* deploy/Assessments/Week6/student-management/
          mkdir -p deploy/Project2/Day2-portfolio
          cp -r Project2/Day2-portfolio/dist/portfolio/browser/* deploy/Project2/Day2-portfolio/
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: deploy

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4